spring:
  cloud:
    gateway:
      routes:
        - id: dev-user-service
          uri: http://localhost:7000/
          predicates:
            - Path=/dev/api/user/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, LoggingFilter
                preLogger: true
                postLogger: true
