spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: dev-user-service
          uri: http://localhost:7000/
          predicates:
            - Path=/dev/api/user/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, LoggingFilter
                preLogger: true
                postLogger: true
#        - id: live-user-service
#          uri: lb://LIVE-USER-SERVICE
#          predicates:
#            - Path=/live/api/user/**
#          filters:
#            - CustomFilter
